#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countApplesAndOranges' function below.
#
# The function accepts following parameters:
#  1. INTEGER s
#  2. INTEGER t
#  3. INTEGER a
#  4. INTEGER b
#  5. INTEGER_ARRAY apples
#  6. INTEGER_ARRAY oranges
#
distance_apples= []
distance_oranges =[]


def countApplesAndOranges(s, t, a, b, apples, oranges):
    # Write your code here

    count_apples=0
    count_oranges=0
    
    for i in apples:
        r = i + a
        distance_apples.append(r)
        
    for j in oranges:
        r = j + b
        distance_oranges.append(r)
    
    for i in distance_apples:
        if i>= s and i<= t:
            #print(i)
            count_apples+=1
        else:
            pass
        
    for j in distancee_oranges:
        if j>= s and j<= t:
       
            count_oranges+=1
        else:
            pass
 
    return(str(count_apples))
    return(str(count_oranges))
    
    

if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    s = int(first_multiple_input[0])

    t = int(first_multiple_input[1])

    second_multiple_input = input().rstrip().split()

    a = int(second_multiple_input[0])

    b = int(second_multiple_input[1])

    third_multiple_input = input().rstrip().split()

    m = int(third_multiple_input[0])

    n = int(third_multiple_input[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
