#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#

r =[]

def gradingStudents(grades):
    for i in grades:
        
        if i > 37:
            tens = (i//10)*10
            #print(tens+5-i)
            
            if (tens+5 - i) <3 and (tens+5 - i) >0:
                
                result = tens+5
                #print(result)
                r.append(result)
            elif (tens+10 - i) < 3:
                
                result = tens+10
                #print(result)
                r.append(result)
            elif (tens+10 - i) == 3 or (tens+5 - (i)) == 3:
                result = i
                #print(result)
                r.append(result)
            else:
                r.append(i)
        
        else:
        
            r.append(i)
            
            
            
    
    return(r)
    

    
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    grades_count = int(input().strip())

    grades = []

    for _ in range(grades_count):
        grades_item = int(input().strip())
        grades.append(grades_item)

    result = gradingStudents(grades)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
