#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'kangaroo' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. INTEGER x1
#  2. INTEGER v1
#  3. INTEGER x2
#  4. INTEGER v2
#

def kangaroo(x1, v1, x2, v2):
    # Write your code here
    
    n_times =1
    distancex1 = x1+v1
    distancex2 = x2+v2
    
    
    if abs(distancex2/distancex1) >3:
        return('NO')
        
    else:
        while 1<=n_times<=10000:
            
            if distancex1 == distancex2:
                return('YES')
                
            else:
                distancex1 = v1+ distancex1 
                distancex2 = v2 + distancex2
            n_times+=1
            
    
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    x1 = int(first_multiple_input[0])

    v1 = int(first_multiple_input[1])

    x2 = int(first_multiple_input[2])

    v2 = int(first_multiple_input[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(result + '\n')

    fptr.close()
